//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace musicapp
{
    using System;
    using System.Collections.Generic;
    
    public partial class song
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public song()
        {
            this.detailplaylists = new HashSet<detailplaylist>();
        }
    
        public int idsong { get; set; }
        public string namesong { get; set; }
        public string imagesong { get; set; }
        public int idsinger { get; set; }
        public int idauthor { get; set; }
        public int idkind { get; set; }
        public string linkgoogle { get; set; }
    
        public virtual author author { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detailplaylist> detailplaylists { get; set; }
        public virtual kind kind { get; set; }
        public virtual singer singer { get; set; }
    }
}
